import { Button, VerticalBox , LineEdit} from "std-widgets.slint";



export component AppWindow inherits Window {
    background: #fdd;
    in property <string> results: ""; // private property
    in-out property <bool> opencurtain;
    callback divide-income(string);
    // width: 200px;
    // height: 200px;
    GridLayout {
        spacing: 150px;
        padding: 50px;
        Row {
            Text {
                text: "Calculator";
                horizontal-alignment: center;
                color: blue;
                font-weight: 900;
                font-size: 16px;
            }
        }
        Row {
            inputText := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter amount here";
                height: 35px;
            }
        }
        Row {
            Button {
                text: "Calculate";
                primary: true;

                height: 35px;
                clicked => {
                    opencurtain = !opencurtain;
                    divide-income(inputText.text)
                }
            }    
        }
        Row {
            Rectangle {
                height: 100px;
                background: #f2f2f2;
                Text {
                    color: black;
                    font-size: 16px;
                    font-weight: 500;
                    text: root.results;
                }
                //Left rectangle
                Rectangle {
                    background: #333;
                    x: 0;
                    width: opencurtain ? 0px : parent.width/2;
                    height: parent.height;
                    animate width {
                        duration: 250ms;
                        easing: ease-in;
                         
                    }
                }
                //right rectangle
                Rectangle {
                    background: #333;
                    x: opencurtain ? parent.width: parent.width/2; 
                    width: opencurtain ? 0px : parent.width/2;
                    height: parent.height;
                    animate width {
                        duration: 250ms;
                        easing: ease-in;
                    }
                    animate x {
                        duration: 250ms;
                        easing: ease-in;
                    }
                }


            }
        }
    }
}
