import { Button, VerticalBox , LineEdit} from "std-widgets.slint";



export component AppWindow inherits Window {
    background: #fdd;
    in property <string> results: ""; // private property
    callback divide-income(string);
    // width: 200px;
    // height: 200px;
    GridLayout {
        spacing: 150px;
        padding: 50px;
        Row {
            Text {
                text: "Calculator";
                horizontal-alignment: center;
                color: blue;
                font-weight: 900;
                font-size: 16px;
            }
        }
        Row {
            inputText := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter amount here";
                height: 35px;
            }
        }
        Row {
            Button {
                text: "Calculate";
                primary: true;

                height: 35px;
                clicked => {divide-income(inputText.text)}
            }    
        }
        Row {
            Rectangle {
                height: 100px;
                background: #f2f2f2;
                Text {
                    color: black;
                    font-size: 16px;
                    font-weight: 500;
                    text: root.results;
                }
            }
        }
    }
}
